[package]
name = "wasi_benchmarking"
version = "0.1.0"
edition = "2021"

[features]
ML = ["wasi-nn"]

[dependencies]
anyhow = "1.0"
fraction = "0.11"
num-bigint = "0.4"
num-traits = "0.2"
wasi-nn = { version = "0.1.0", optional = true }